server:
  error:
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime?useSSL=false
    username: root
    password: docker
  jpa:
    hibernate:
      ddl-auto: update